// 4xx Client Errors
export const BAD_REQUEST = 'BAD_REQUEST'
export const UNAUTHORIZED = 'UNAUTHORIZED'
export const PAYMENT_REQUIRED = 'PAYMENT_REQUIRED'
export const FORBIDDEN = 'FORBIDDEN'
export const NOT_FOUND = 'NOT_FOUND'
export const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
export const NOT_ACCEPTABLE = 'NOT_ACCEPTABLE'
export const PROXY_AUTHENTICATION_REQUIRED = 'PROXY_AUTHENTICATION_REQUIRED'
export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT'
export const CONFLICT = 'CONFLICT'
export const GONE = 'GONE'
export const LENGTH_REQUIRED = 'LENGTH_REQUIRED'
export const PRECONDITION_FAILED = 'PRECONDITION_FAILED'
export const PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE'
export const URI_TOO_LONG = 'URI_TOO_LONG'
export const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE'
export const RANGE_NOT_SATISFIABLE = 'RANGE_NOT_SATISFIABLE'
export const EXPECTATION_FAILED = 'EXPECTATION_FAILED'
export const IM_A_TEAPOT = 'IM_A_TEAPOT'
export const UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY'
export const LOCKED = 'LOCKED'
export const FAILED_DEPENDENCY = 'FAILED_DEPENDENCY'
export const TOO_EARLY = 'TOO_EARLY'
export const UPGRADE_REQUIRED = 'UPGRADE_REQUIRED'
export const PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED'
export const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
export const REQUEST_HEADER_FIELDS_TOO_LARGE = 'REQUEST_HEADER_FIELDS_TOO_LARGE'
export const UNAVAILABLE_FOR_LEGAL_REASONS = 'UNAVAILABLE_FOR_LEGAL_REASONS'

// 5xx Server Errors
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
export const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
export const BAD_GATEWAY = 'BAD_GATEWAY'
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
export const GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT'
export const HTTP_VERSION_NOT_SUPPORTED = 'HTTP_VERSION_NOT_SUPPORTED'
export const VARIANT_ALSO_NEGOTIATES = 'VARIANT_ALSO_NEGOTIATES'
export const INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE'
export const LOOP_DETECTED = 'LOOP_DETECTED'
export const NOT_EXTENDED = 'NOT_EXTENDED'
export const NETWORK_AUTHENTICATION_REQUIRED = 'NETWORK_AUTHENTICATION_REQUIRED'

export const ERROR_CODE = {
  // 4xx Client Errors
  '400': BAD_REQUEST,
  '401': UNAUTHORIZED,
  '402': PAYMENT_REQUIRED,
  '403': FORBIDDEN,
  '404': NOT_FOUND,
  '405': METHOD_NOT_ALLOWED,
  '406': NOT_ACCEPTABLE,
  '407': PROXY_AUTHENTICATION_REQUIRED,
  '408': REQUEST_TIMEOUT,
  '409': CONFLICT,
  '410': GONE,
  '411': LENGTH_REQUIRED,
  '412': PRECONDITION_FAILED,
  '413': PAYLOAD_TOO_LARGE,
  '414': URI_TOO_LONG,
  '415': UNSUPPORTED_MEDIA_TYPE,
  '416': RANGE_NOT_SATISFIABLE,
  '417': EXPECTATION_FAILED,
  '418': IM_A_TEAPOT,
  '422': UNPROCESSABLE_ENTITY,
  '423': LOCKED,
  '424': FAILED_DEPENDENCY,
  '425': TOO_EARLY,
  '426': UPGRADE_REQUIRED,
  '428': PRECONDITION_REQUIRED,
  '429': TOO_MANY_REQUESTS,
  '431': REQUEST_HEADER_FIELDS_TOO_LARGE,
  '451': UNAVAILABLE_FOR_LEGAL_REASONS,

  // 5xx Server Errors
  '500': INTERNAL_SERVER_ERROR,
  '501': NOT_IMPLEMENTED,
  '502': BAD_GATEWAY,
  '503': SERVICE_UNAVAILABLE,
  '504': GATEWAY_TIMEOUT,
  '505': HTTP_VERSION_NOT_SUPPORTED,
  '506': VARIANT_ALSO_NEGOTIATES,
  '507': INSUFFICIENT_STORAGE,
  '508': LOOP_DETECTED,
  '510': NOT_EXTENDED,
  '511': NETWORK_AUTHENTICATION_REQUIRED,
} as const
